on:
  pull_request:
  workflow_dispatch:

name: coverage

permissions: read-all

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
      - name: Measure coverage
        run: |
          coverage <- covr::package_coverage()
          print(coverage)
          percentage <- covr::percent_coverage(coverage)
          if (percentage < 90) {
            stop(
              sprintf(
                "Cobertura %.2f%% abaixo do mínimo de 90%%.",
                percentage
              )
            )
          }
          covr::report(coverage, file = "coverage.html")
        shell: Rscript {0}
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html
